name: "preprocess"
backend: "python"
max_batch_size: 256 
input [
{
    name: "PREPROCESS_INPUT_0"
    data_type: TYPE_UINT8
    dims: [3, 1080, 1920]
}
]
 
output [
{
    name: "PREPROCESS_OUTPUT_0"
    data_type: TYPE_FP32
    dims: [3, 224, 224]
}
]

instance_group [{ kind: KIND_CPU }]